# Библиотеки

In [1]:
import os
import json
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\4112017540.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\4112017540.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\4112017540.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\vedma\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\4112017540.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\vedma\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\vedma\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

C:\Users\vedma\anaconda3\Lib\site-packages\sklearn\utils\__init__.py:16: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.3.5)
  from scipy.sparse import issparse

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\4112017540.py", line 6, in <module>
    from sklearn.preprocessing import StandardScaler
  File "C:\Users\vedma\anaconda3\Lib\site-packages\sklearn\__init__.py", line 87, in <module>
    from .base import clone
  File "C:\Users\vedma\anaconda3\Lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\vedma\anaconda3\Lib\site-packages\sklearn\utils\__init__.py", line 16, in <module>
    from scipy.sparse import issparse
  File "C:\Users\vedma\anaconda3\Lib\site-packages\scipy\sparse\__init__.py", line 295, in <module>
    from ._csr import *
  File "C:\Users\vedma\anaconda3\Lib\site-packages\scipy\sparse\_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

# CHECKPOINT 1

# Полный CSV

In [3]:
metadata_dir = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_json"

files = [f for f in os.listdir(metadata_dir) if f.endswith(".json")]
rows = []

for file in tqdm(files):
    path = os.path.join(metadata_dir, file)
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    row = {
        "id": data.get("id"),
        "name": data.get("name"),
        "duration": data.get("duration"),
        "artist_id": data.get("artist_id"),
        "artist_name": data.get("artist_name"),
        "album_id": data.get("album_id"),
        "album_name": data.get("album_name"),
        "releasedate": data.get("releasedate"),
    }

    mi = data.get("musicinfo", {})
    row["lang"] = mi.get("lang")
    row["vocalinstrumental"] = mi.get("vocalinstrumental")
    row["gender"] = mi.get("gender")
    row["acousticelectric"] = mi.get("acousticelectric")
    row["speed"] = mi.get("speed")

    tags = mi.get("tags", {})
    row["genres"] = ", ".join(tags.get("genres", []))
    row["instruments"] = ", ".join(tags.get("instruments", []))
    row["vartags"] = ", ".join(tags.get("vartags", []))

    st = data.get("stats", {})
    row["rate_downloads_total"] = st.get("rate_downloads_total")
    row["rate_listened_total"] = st.get("rate_listened_total")
    row["playlisted"] = st.get("playlisted")
    row["favorited"] = st.get("favorited")
    row["likes"] = st.get("likes")
    row["dislikes"] = st.get("dislikes")
    row["avgnote"] = st.get("avgnote")

    rows.append(row)

df = pd.DataFrame(rows)

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_full.csv"
df.to_csv(out_path, index=False, encoding="utf-8-sig")

100%|█████████████████████████████████████████████████████████████████████████████| 2001/2001 [00:13<00:00, 145.28it/s]

# Проверки

In [5]:
display(df.head())

,id,name,duration,artist_id,artist_name,album_id,album_name,releasedate,lang,vocalinstrumental,...,genres,instruments,vartags,rate_downloads_total,rate_listened_total,playlisted,favorited,likes,dislikes,avgnote
0,1000957,Key to Success - Discover the Possibility,170,375935,Akashic Records,117782,Corporate Presentation - Key To Success,2013-01-20,,instrumental,...,"corporate, filmscore, poprock","guitar, strings","motivational, happy, film",136505,598523,1999,843,27,1,8.2857
1,1001519,In Your Face,201,1333,Brad Sucks,117853,Guess Who's a Mess,2013-01-22,,vocal,...,,,,91080,518129,270,151,20,1,8.6667
2,1002052,Feel Good Acoustic Ukulele,213,375935,Akashic Records,117912,Optimistic Acoustic Ukulele,2013-01-23,,instrumental,...,"pop, folk, filmscore","strings, ukulele","happy, advertising, peaceful",123720,406731,1490,744,78,1,8.9231
3,1007842,Heaven by Bruno Susio (feat. Marie Louise Frif...,263,365833,Jazz Friends,118676,Jazz Friends 2013 - Guitars in Jazz,2013-02-14,,vocal,...,jazz,"drums, electricguitar","vocal, upbeat, voice, loungejazz",15935,186017,81,29,6,0,8.0000
4,1007988,Do or Die,240,367351,Fall Walk Run,118643,Piece By Piece,2013-02-12,,vocal,...,rock,,"vocal, voice",195521,732900,626,338,73,4,8.3333

In [7]:
df[df["id"] == '1157362']

,id,name,duration,artist_id,artist_name,album_id,album_name,releasedate,lang,vocalinstrumental,...,genres,instruments,vartags,rate_downloads_total,rate_listened_total,playlisted,favorited,likes,dislikes,avgnote
274,1157362,First,204,440692,JekK,138887,Dear Dreams,2014-09-28,en,vocal,...,"dance, edm","synthesizer, piano","happy, energetic, advertising, voice",3639776,6961521,6308,3986,220,12,9.8667

In [9]:
df.nunique()

id                      2001
name                    1959
duration                 333
artist_id                669
artist_name              668
album_id                1065
album_name              1055
releasedate              946
lang                       9
vocalinstrumental          3
gender                     4
acousticelectric           3
speed                      6
genres                   785
instruments              222
vartags                 1069
rate_downloads_total    1978
rate_listened_total     1998
playlisted              1237
favorited               1005
likes                    113
dislikes                  19
avgnote                   96
dtype: int64

# Сэмпл 250 треков, охватывающий все существующие комбинации значений в колонках: 'lang', 'vocalinstrumental', 'gender', 'acousticelectric', 'speed' и 'instruments'

In [12]:
cols = ['lang', 'vocalinstrumental', 'gender', 'acousticelectric', 'speed', 'instruments']

frames = []
for col in cols:
    unique_vals = df[col].unique()
    for val in unique_vals:
        sample_row = df[df[col] == val].head(1)
        frames.append(sample_row)

df_repr = pd.concat(frames).drop_duplicates().reset_index(drop=True)


add_rows = df.sample(250 - len(df_repr)+6, random_state=250)
df_repr = pd.concat([df_repr, add_rows]).drop_duplicates().head(250).reset_index(drop=True)

print("Количество уникальных значений по колонкам:")
print(df_repr[cols].nunique())
display(df_repr)

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_sample_250.csv"
df_repr.to_csv(out_path, index=False, encoding="utf-8-sig")

Количество уникальных значений по колонкам:
lang                   9
vocalinstrumental      3
gender                 4
acousticelectric       3
speed                  6
instruments          222
dtype: int64

,id,name,duration,artist_id,artist_name,album_id,album_name,releasedate,lang,vocalinstrumental,...,genres,instruments,vartags,rate_downloads_total,rate_listened_total,playlisted,favorited,likes,dislikes,avgnote
0,1000957,Key to Success - Discover the Possibility,170,375935,Akashic Records,117782,Corporate Presentation - Key To Success,2013-01-20,,instrumental,...,"corporate, filmscore, poprock","guitar, strings","motivational, happy, film",136505,598523,1999,843,27,1,8.2857
1,1009673,Endless Hours,168,7063,Fresh Body Shop,118858,Wizard,2013-02-19,en,vocal,...,"rock, pop",,"acoustic, vocal, voice, neutral",10463,688604,162,74,5,1,8.0000
2,1014954,Qué Pasó,217,358187,Sundayers,119528,Impulsos,2013-03-12,es,vocal,...,"reggae, rock",,"vocal, happy, voice",29812,223571,270,152,1,0,8.0000
3,1027698,La Scelta del Presidente,197,351372,Millionaire Blonde,120852,La Scelta del Presidente,2013-04-19,it,vocal,...,"pop, electronic, electropop","synthesizer, violin","energetic, acoustic, vocal, voice",331754,1616864,440,221,55,3,8.0357
4,10558,A l’orée d’un siècle en bois,235,14,David TMX,1561,A l'orée d'un siecle en bois,2006-03-29,fr,vocal,...,metal,,"acoustic, vocal, voice, neutral",9205,44769,1744,1540,0,0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,35349,do it over,184,4927,amélie,4301,be low,2007-02-12,en,vocal,...,"pop, rock",,"acoustic, vocal, voice",107347,1070584,2220,828,9,1,7.2500
246,15664,Headphonetic,396,2278,Revolution Void,2225,Increase the Dosage,2006-06-20,,instrumental,...,"ambient, electronic, downtempo",saxophone,"psychedelic, soft, peaceful",51787,572962,4197,3158,5,1,8.6667
247,537123,¿Quién Debe a Quién?,249,358187,Sundayers,62611,Cógelo!,2010-03-05,es,vocal,...,"reggae, rock",,"acoustic, vocal, voice",10814,160642,393,232,0,0,9.0000
248,1159406,Spark,224,444388,Final Round,139192,It Ends with Us Both Right Here EP,2014-10-10,,vocal,...,"rock, poppunk","electricguitar, drums","energetic, vocal, fast, voice",130469,335578,617,338,53,4,8.6667
249,744750,You Are You,173,367351,Fall Walk Run,87031,Throwing It All Away,2011-03-10,,vocal,...,,,,115131,583524,308,149,14,0,8.6667

# CSV с фичами

#### Z-преобразование

In [16]:
numeric_cols = ['duration', 'rate_downloads_total',	'rate_listened_total', 'playlisted', 'favorited', 'likes', 'dislikes', 'avgnote']

df_scaled = df.copy()

scaler = StandardScaler() 
df_scaled[numeric_cols] = scaler.fit_transform(df_scaled[numeric_cols])

display(df_scaled[numeric_cols].describe().round(2))

NameError: name 'StandardScaler' is not defined

#### Максимум большинства колонок слишком большой, можно прибегнуть к их логарифмированию

#### Z-преобразование с логарифмированием (для снижения веса больших разрывов)

In [35]:
df_scaled = df.copy()

cols_to_log = ["duration", "rate_downloads_total", "rate_listened_total", "likes", "dislikes"]

for col in cols_to_log:
    df_scaled[col + "_log"] = np.log1p(df_scaled[col])

numeric_cols = [col + "_log" for col in cols_to_log] + ["playlisted", "favorited", "avgnote"]

scaler = StandardScaler()
scaled_values = scaler.fit_transform(df_scaled[numeric_cols])

scaled_cols = [col + "_scaled" for col in numeric_cols]
df_scaled[scaled_cols] = scaled_values

display(df_scaled[scaled_cols].describe().round(2))

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_only_scaled_features.csv"
df_scaled[scaled_cols].to_csv(out_path, index=False, encoding="utf-8-sig")

df_scaled = df_scaled.drop(df_scaled.columns[23:28], axis=1)
display(df_scaled[scaled_cols])

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_with_scaled_features.csv"
df_scaled.to_csv(out_path, index=False, encoding="utf-8-sig")

NameError: name 'StandardScaler' is not defined

#### OHE для колонок: "lang", "vocalinstrumental", "gender", "acousticelectric", "speed"

In [20]:
df_encoded = df_scaled.copy()

cat_cols = ["lang", "vocalinstrumental", "gender", "acousticelectric", "speed"]

df_encoded = pd.get_dummies(df_encoded, columns=cat_cols, prefix=cat_cols)

ohe_cols = [col for col in df_encoded.columns if any(x in col for x in cat_cols)]
display(df_encoded[ohe_cols])

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_only_ohe_features.csv"
df_encoded[ohe_cols].to_csv(out_path, index=False, encoding="utf-8-sig")

,lang_,lang_de,lang_en,lang_es,lang_fr,lang_id,lang_it,lang_pt,lang_zh,vocalinstrumental_,...,gender_neutral,acousticelectric_,acousticelectric_acoustic,acousticelectric_electric,speed_,speed_high,speed_low,speed_medium,speed_veryhigh,speed_verylow
0,True,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
2,True,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,False,True,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
1997,True,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
1998,False,False,True,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
1999,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False
2000,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,True,False,False

#### Подсчет количества жанров, инструментов и тегов + наличие часто встречающихся (более 100 раз)

In [23]:
import pandas as pd

df_tags = df_encoded.copy()

df_tags["genres_count"] = df_tags["genres"].apply(
    lambda x: len(str(x).split(", ")) if pd.notnull(x) else 0
)
df_tags["instruments_count"] = df_tags["instruments"].apply(
    lambda x: len(str(x).split(", ")) if pd.notnull(x) else 0
)
df_tags["vartags_count"] = df_tags["vartags"].apply(
    lambda x: len(str(x).split(", ")) if pd.notnull(x) else 0
)

def make_binary_tags(df, col, min_count=100):
    all_tags = df[col].dropna().str.split(", ").sum()
    counts = pd.Series(all_tags).value_counts()
    frequent = counts[counts >= min_count].index
    for tag in frequent:
        tag_col = f"has_{col}_{tag.replace(' ', '_')}"
        df[tag_col] = df[col].apply(lambda x: 1 if pd.notnull(x) and tag in x else 0)
    return df

for col in ["genres", "instruments", "vartags"]:
    df_tags = make_binary_tags(df_tags, col)

new_cols = [c for c in df_tags.columns if c.endswith("_count") or c.startswith("has_")]
display(df_tags[new_cols].columns)
display(df_tags[new_cols])

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_only_tag_features.csv"
df_tags[new_cols].to_csv(out_path, index=False, encoding="utf-8-sig")

Index(['genres_count', 'instruments_count', 'vartags_count', 'has_genres_pop',
       'has_genres_rock', 'has_genres_electronic', 'has_genres_jazz',
       'has_genres_', 'has_genres_indie', 'has_genres_folk',
       'has_genres_chillout', 'has_instruments_', 'has_instruments_strings',
       'has_instruments_piano', 'has_instruments_synthesizer',
       'has_instruments_guitar', 'has_instruments_drums',
       'has_instruments_electricguitar', 'has_vartags_voice',
       'has_vartags_vocal', 'has_vartags_acoustic', 'has_vartags_',
       'has_vartags_neutral', 'has_vartags_peaceful', 'has_vartags_energetic',
       'has_vartags_happy', 'has_vartags_love', 'has_vartags_upbeat'],
      dtype='object')

,genres_count,instruments_count,vartags_count,has_genres_pop,has_genres_rock,has_genres_electronic,has_genres_jazz,has_genres_,has_genres_indie,has_genres_folk,...,has_vartags_voice,has_vartags_vocal,has_vartags_acoustic,has_vartags_,has_vartags_neutral,has_vartags_peaceful,has_vartags_energetic,has_vartags_happy,has_vartags_love,has_vartags_upbeat
0,3,2,3,1,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
1,1,1,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
2,3,2,3,1,0,0,0,1,0,1,...,0,0,0,1,0,1,0,1,0,0
3,1,2,4,0,0,0,1,1,0,0,...,1,1,0,1,0,0,0,0,0,1
4,1,1,2,0,1,0,0,1,0,0,...,1,1,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,3,1,1,0,1,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
1997,2,1,3,1,0,1,0,1,0,0,...,1,1,1,1,0,0,0,0,0,0
1998,1,1,3,1,0,0,0,1,0,0,...,1,1,1,1,0,0,0,0,0,0
1999,1,1,3,0,0,0,0,1,0,0,...,1,1,0,1,0,0,0,1,0,0
2000,1,1,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0

#### Объединение в один ДФ фичей

In [26]:
features_df = pd.concat([df_scaled[scaled_cols], df_tags[new_cols], df_encoded[ohe_cols]], axis=1)
display(features_df)

out_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_all_features.csv"
features_df.to_csv(out_path, index=False, encoding="utf-8-sig")

NameError: name 'scaled_cols' is not defined

# ТОП-5 по числовым признакам

In [29]:
num_cols = ["duration", "rate_downloads_total", "rate_listened_total", "playlisted", "favorited", "likes", "dislikes", "avgnote"]

for col in num_cols:
    print(f"ПРИЗНАК --- {col.upper()}")

    df_sorted_min = df.sort_values(by=col, ascending=True)
    top5_min = df_sorted_min.head(5)

    if top5_min[col].nunique() == 1:
        val = top5_min[col].iloc[0]
        res_min = df_sorted_min[df_sorted_min[col] == val]
        print(f"Все минимальные значения")
    else:
        res_min = top5_min
        print("ТОП-5 минимальных значений:")

    display(res_min[["id", "name", "artist_name", col]])

    df_sorted_max = df.sort_values(by=col, ascending=False)
    top5_max = df_sorted_max.head(5)

    if top5_max[col].nunique() == 1:
        val = top5_max[col].iloc[0]
        res_max = df_sorted_max[df_sorted_max[col] == val]
        print(f"Все максимальные значения")
    else:
        res_max = top5_max
        print("ТОП-5 максимальных значений:")

    display(res_max[["id", "name", "artist_name", col]])

ПРИЗНАК --- DURATION
ТОП-5 минимальных значений:

,id,name,artist_name,duration
78,10579,Je m’appelle crogrignnnoncr,David TMX,4
241,1131496,Heart,Paolo Pavan,50
1786,785431,Petite chanson grivoise - INSTRUMENTAL VERSION,Löhstana David,54
1370,391008,Qualms of Conscience,Diablo Swing Orchestra,76
1915,944914,plaid shirt (revisited),Ton,82

ТОП-5 максимальных значений:

,id,name,artist_name,duration
490,1243867,"Springtime Meditation (Music for Meditation, W...",Hannes Hofkind,1196
785,1539824,Blancoz - La solita storia pt.2,Blancoz,953
1986,9884,"The Artist, The Sage, and The Jester",JT Bruce,900
1332,355479,Hand In Space,Quantum Jazz,741
505,1250829,Solar Plexus Chakra - (note E),Macroform,631

ПРИЗНАК --- RATE_DOWNLOADS_TOTAL
ТОП-5 минимальных значений:

          id            name         artist_name  rate_downloads_total
1405  425159          Yasoil            Jazz Oil                  2076
75     10576       Imbroglio           David TMX                  2716
1634  661634            Left             JoosTVD                  2730
1911  939901         Wall #4  Basement Skylights                  2850
1610  644669  The Submissive          Malika Rai                  3022

ТОП-5 максимальных значений:

,id,name,artist_name,rate_downloads_total
1068,1932670,RED LIGHT,Egor Budennyy,16719048
429,1214935,Wish You Were Here,The.madpix.project,14483187
374,1204669,What Is Love,Melanie Ungar,8900915
256,1141572,Love Will Come Back Again,Chaz Robinson,7512436
228,1129271,Energy,Pokki DJ,3924453

ПРИЗНАК --- RATE_LISTENED_TOTAL
ТОП-5 минимальных значений:

       id                    name artist_name  rate_listened_total
71  10573                  Tabass   David TMX                11784
75  10576               Imbroglio   David TMX                12228
74  10575  Knoklezout au taquet !   David TMX                12736
68  10570       L’homme s’enterre   David TMX                13472
77  10578             Border line   David TMX                13721

ТОП-5 максимальных значений:

,id,name,artist_name,rate_listened_total
429,1214935,Wish You Were Here,The.madpix.project,24847640
1355,381092,Ils marchent,Soul Connexion,15160551
374,1204669,What Is Love,Melanie Ungar,13718148
256,1141572,Love Will Come Back Again,Chaz Robinson,10690861
1323,35106,Afrique,Andrea Barone,8933977

ПРИЗНАК --- PLAYLISTED
ТОП-5 минимальных значений:

,id,name,artist_name,playlisted
621,1396152,Lagu_Buat_Kamu_-_Aldi_indiana_yusuf,Aldi indiana yusuf,1
785,1539824,Blancoz - La solita storia pt.2,Blancoz,2
318,1172514,09 Fubu - Entre Nos,Dj Fubu G our Fubu G,10
73,1057482,Sorry,Dayung,12
1526,548764,Fuori Posto,GUCCIO GIOVANNI,17

ТОП-5 максимальных значений:

           id                name             artist_name  playlisted
429   1214935  Wish You Were Here      The.madpix.project       10167
1214    26736           Struttin'                   Tryad        8831
1364   391002       Balrog Boogie  Diablo Swing Orchestra        8598
1215    26737             Breathe                   Tryad        8411
1220    26742              Beauty                   Tryad        7962

ПРИЗНАК --- FAVORITED
ТОП-5 минимальных значений:

,id,name,artist_name,favorited
621,1396152,Lagu_Buat_Kamu_-_Aldi_indiana_yusuf,Aldi indiana yusuf,0
785,1539824,Blancoz - La solita storia pt.2,Blancoz,1
318,1172514,09 Fubu - Entre Nos,Dj Fubu G our Fubu G,2
1526,548764,Fuori Posto,GUCCIO GIOVANNI,4
1836,856526,Musica,Fabrizio Ciccarelli,4

ТОП-5 максимальных значений:

           id                      name         artist_name  favorited
429   1214935        Wish You Were Here  The.madpix.project       6221
1214    26736                 Struttin'               Tryad       5745
1215    26737                   Breathe               Tryad       5621
1225    26747  Waltz Into the Moonlight               Tryad       5513
1220    26742                    Beauty               Tryad       5500

ПРИЗНАК --- LIKES
Все минимальные значения

,id,name,artist_name,likes
534,1291394,Home,The Grus,0
532,1290896,GO!GO!GO! HateTheBoyfriend AllTheWayRemix,Emerald Park,0
531,1289529,Maximize,Alumo,0
530,1289523,Plug it In,Alumo,0
528,1284793,SMILING FACES,jean-yves allaire,0
...,...,...,...,...
983,1823855,Losing Ground,Luke Davids,0
989,1826189,Not the One to Say (I Told You So) (24-bit Mas...,Cole Powell,0
990,1826504,Greedy - Kyrie Braxton,Kyrie Braxton,0
7,1011643,Daily Routine,Kingston Blues,0
9,101464,Hello Black & White Bird,The Old Dada Weatherman,0

ТОП-5 максимальных значений:

          id                         name     artist_name  likes
153  1099703  Divergence (Remastered VIP)  TheBlackParrot    471
219  1122085                        Sweet   Tamara Laurel    394
132  1092425                April Showers        ProleteR    392
228  1129271                       Energy        Pokki DJ    326
146  1093987                        Sweet   Tamara Laurel    295

ПРИЗНАК --- DISLIKES
Все минимальные значения

           id                  name          artist_name  dislikes
1996   992660                 Day-X              Sunwill         0
1994   992658           Stereo Time              Sunwill         0
1989     9887              Viridian             JT Bruce         0
1988     9886  The Towers of Mirria             JT Bruce         0
1987     9885   The Pioneer Anomaly             JT Bruce         0
...       ...                   ...                  ...       ...
24    1031199    Thanks for Nothing  Great White Buffalo         0
28     103599           Electricity        Alexander Blu         0
29     103614                 River        Alexander Blu         0
31    1036439       NOTHING REACTED           Sweet Play         0
1984     9882     Shoulder of Orion             JT Bruce         0

[1351 rows x 4 columns]

ТОП-5 максимальных значений:

           id                            name     artist_name  dislikes
153   1099703     Divergence (Remastered VIP)  TheBlackParrot        27
1330   354778  Skydiving (feat. Jasmine Kara)           Jonay        22
256   1141572       Love Will Come Back Again   Chaz Robinson        22
1712   744648                   A Common Tale      Radio Star        17
228   1129271                          Energy        Pokki DJ        17

ПРИЗНАК --- AVGNOTE
Все минимальные значения

          id                           name    artist_name  avgnote
1989    9887                       Viridian       JT Bruce      0.0
1988    9886           The Towers of Mirria       JT Bruce      0.0
1987    9885            The Pioneer Anomaly       JT Bruce      0.0
54     10558  A l’orée d’un siècle en bois       David TMX      0.0
60     10562   Brojzdi abroujzdaniev vizjda      David TMX      0.0
...      ...                            ...            ...      ...
1941     955                         Spider  Alexander Blu      0.0
1623    6573    Beat Into Submission (Solo)          Tryad      0.0
1569  591583          Pieces of a Past Life    The Postmen      0.0
1662    6956               There is a place     Drunksouls      0.0
1568  591582         Lady From Way up There    The Postmen      0.0

[87 rows x 4 columns]

Все максимальные значения

           id                               name      artist_name  avgnote
1969   975249                      see you again             Rexo     10.0
391   1210694                      One Step Away  Fresh Body Shop     10.0
395   1210700                             Wizard  Fresh Body Shop     10.0
406    121142                            Al Gore       Triplexity     10.0
550   1309301                           The Heat      Sam Garbett     10.0
...       ...                                ...              ...      ...
947   1781142                      Talk a Little      Samie Bower     10.0
383   1207077  ANtarcticbreeze - Round the World  ANtarcticbreeze     10.0
948   1781573              Heart of a Lion (Leo)            RENAE     10.0
949   1784196                             Yellow        Sam Opoku     10.0
932   1744247                    Walk in the row         RedSharp     10.0

[93 rows x 4 columns]

# Проверка гипотез

#### Вариативность фичей внутри артиста

In [33]:
import matplotlib.pyplot as plt
import seaborn as sns

artist_var = df_scaled[scaled_cols].groupby(df["artist_name"]).var().mean(axis=1)
plt.figure(figsize=(7,4))
sns.histplot(artist_var, bins=30)
plt.title("Средняя вариативность фичей внутри артиста")
plt.xlabel("Среднее внутригрупповое std по фичам")
plt.ylabel("Количество артистов")
plt.show()

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\vedma\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\vedma\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vedma\AppData\Local\Temp\ipykernel_27128\2081687815.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\vedma\anaconda3\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

#### В большинстве своем, признаки треков одного артиста не сильно отличаются. Можно предположить, что если пользователю понравился один трек артиста, значит с большой долей вероятности понравится и другой

#### Зависимость успеха трека от количества жанров в нем

In [35]:
plt.figure(figsize=(15, 10))

plt.subplot(3, 3, 1)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["likes_log_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Лайки")
plt.xlabel("Количество жанров")
plt.ylabel("Лайки (лог, стандартиз.)")

plt.subplot(3, 3, 2)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["rate_listened_total_log_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Прослушивания")
plt.xlabel("Количество жанров")
plt.ylabel("Прослушивания (лог, стандартиз.)")

plt.subplot(3, 3, 3)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["rate_downloads_total_log_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Скачивания")
plt.xlabel("Количество жанров")
plt.ylabel("Скачивания (лог, стандартиз.)")

plt.subplot(3, 3, 4)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["playlisted_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Плейлисты")
plt.xlabel("Количество жанров")
plt.ylabel("Плейлисты (стандартиз.)")

plt.subplot(3, 3, 5)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["dislikes_log_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Дизлайки")
plt.xlabel("Количество жанров")
plt.ylabel("Дизлайки (лог, стандартиз.)")

plt.subplot(3, 3, 6)
sns.scatterplot(
    data=df_tags,
    x="genres_count",
    y=df_scaled["favorited_scaled"],
    alpha=0.6
)
plt.title("Жанры vs Избранное")
plt.xlabel("Количество жанров")
plt.ylabel("Избранное (стандартиз.)")

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

#### Можно заметить, что большее количество жанров влечет большее количество прослушиваний

#### Зависимость успеха трека от скорости

In [39]:
df_merged = pd.merge(
    df[["id", "speed", "lang"]],
    df_scaled[["id", "likes_log_scaled", "rate_listened_total_log_scaled", "rate_downloads_total_log_scaled", "playlisted_scaled", "favorited_scaled", "dislikes_log_scaled"]],
    on="id",
    how="inner"
)
plt.figure(figsize=(15, 9))

plt.subplot(3, 3, 1)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="likes_log_scaled"
)
plt.title("Speed vs Лайки")
plt.xlabel("Скорость трека")
plt.ylabel("Лайки (лог, стандартиз.)")

plt.subplot(3, 3, 2)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="rate_listened_total_log_scaled"
)
plt.title("Speed vs Прослушивания")
plt.xlabel("Скорость трека")
plt.ylabel("Прослушивания (лог, стандартиз.)")

plt.subplot(3, 3, 3)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="rate_downloads_total_log_scaled"
)
plt.title("Speed vs Скачивания")
plt.xlabel("Скорость трека")
plt.ylabel("Скачивания (лог, стандартиз.)")

plt.subplot(3, 3, 4)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="playlisted_scaled"
)
plt.title("Speed vs Плейлисты")
plt.xlabel("Скорость трека")
plt.ylabel("Плейлисты (стандартиз.)")

plt.subplot(3, 3, 5)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="favorited_scaled"
)
plt.title("Speed vs Избранное")
plt.xlabel("Скорость трека")
plt.ylabel("Избранное (стандартиз.)")

plt.subplot(3, 3, 6)
sns.boxplot(
    data=df_merged,
    x="speed",
    y="dislikes_log_scaled"
)
plt.title("Speed vs Дизлайки")
plt.xlabel("Скорость трека")
plt.ylabel("Дизлайки (лог, стандартиз.)")

plt.tight_layout()
plt.show()

KeyError: "['likes_log_scaled', 'rate_listened_total_log_scaled', 'rate_downloads_total_log_scaled', 'playlisted_scaled', 'favorited_scaled', 'dislikes_log_scaled'] not in index"

#### Явных зависимостей не обнаружено

#### Зависимость успеха трека от языка

In [41]:
plt.figure(figsize=(15, 9))

plt.subplot(3, 3, 1)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="likes_log_scaled"
)
plt.title("Lang vs Лайки")
plt.xlabel("Язык трека")
plt.ylabel("Лайки (лог, стандартиз.)")

plt.subplot(3, 3, 2)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="rate_listened_total_log_scaled"
)
plt.title("Lang vs Прослушивания")
plt.xlabel("Язык трека")
plt.ylabel("Прослушивания (лог, стандартиз.)")

plt.subplot(3, 3, 3)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="rate_downloads_total_log_scaled"
)
plt.title("Lang vs Скачивания")
plt.xlabel("Язык трека")
plt.ylabel("Скачивания (лог, стандартиз.)")

plt.subplot(3, 3, 4)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="playlisted_scaled"
)
plt.title("Lang vs Плейлисты")
plt.xlabel("Язык трека")
plt.ylabel("Плейлисты (стандартиз.)")

plt.subplot(3, 3, 5)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="favorited_scaled"
)
plt.title("Lang vs Избранное")
plt.xlabel("Язык трека")
plt.ylabel("Избранное (стандартиз.)")

plt.subplot(3, 3, 6)
sns.boxplot(
    data=df_merged,
    x="lang",
    y="dislikes_log_scaled"
)
plt.title("Lang vs Дизлайки")
plt.xlabel("Язык трека")
plt.ylabel("Дизлайки (лог, стандартиз.)")

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [169]:
csv_path = r"C:\Users\vedma\OneDrive\Рабочий стол\Учеба\HSE project\downloaded_tracks\metadata\metadata_all_features.csv"

features_df = pd.read_csv(csv_path)

print("Форма датафрейма:", features_df.shape)
print("Колонки:", features_df.columns.tolist())

display(features_df.head())

Форма датафрейма: (2001, 61)
Колонки: ['duration_log_scaled', 'rate_downloads_total_log_scaled', 'rate_listened_total_log_scaled', 'likes_log_scaled', 'dislikes_log_scaled', 'playlisted_scaled', 'favorited_scaled', 'avgnote_scaled', 'genres_count', 'instruments_count', 'vartags_count', 'has_genres_pop', 'has_genres_rock', 'has_genres_electronic', 'has_genres_jazz', 'has_genres_', 'has_genres_indie', 'has_genres_folk', 'has_genres_chillout', 'has_instruments_', 'has_instruments_strings', 'has_instruments_piano', 'has_instruments_synthesizer', 'has_instruments_guitar', 'has_instruments_drums', 'has_instruments_electricguitar', 'has_vartags_voice', 'has_vartags_vocal', 'has_vartags_acoustic', 'has_vartags_', 'has_vartags_neutral', 'has_vartags_energetic', 'has_vartags_peaceful', 'has_vartags_happy', 'has_vartags_love', 'has_vartags_upbeat', 'lang_', 'lang_de', 'lang_en', 'lang_es', 'lang_fr', 'lang_id', 'lang_it', 'lang_pt', 'lang_zh', 'vocalinstrumental_', 'vocalinstrumental_instrumental', 'vocalinstrumental_vocal', 'gender_', 'gender_female', 'gender_male', 'gender_neutral', 'acousticelectric_', 'acousticelectric_acoustic', 'acousticelectric_electric', 'speed_', 'speed_high', 'speed_low', 'speed_medium', 'speed_veryhigh', 'speed_verylow']

,duration_log_scaled,rate_downloads_total_log_scaled,rate_listened_total_log_scaled,likes_log_scaled,dislikes_log_scaled,playlisted_scaled,favorited_scaled,avgnote_scaled,genres_count,instruments_count,vartags_count,has_genres_pop,has_genres_rock,has_genres_electronic,has_genres_jazz,has_genres_,has_genres_indie,has_genres_folk,has_genres_chillout,has_instruments_,has_instruments_strings,has_instruments_piano,has_instruments_synthesizer,has_instruments_guitar,has_instruments_drums,has_instruments_electricguitar,has_vartags_voice,has_vartags_vocal,has_vartags_acoustic,has_vartags_,has_vartags_neutral,has_vartags_energetic,has_vartags_peaceful,has_vartags_happy,has_vartags_love,has_vartags_upbeat,lang_,lang_de,lang_en,lang_es,lang_fr,lang_id,lang_it,lang_pt,lang_zh,vocalinstrumental_,vocalinstrumental_instrumental,vocalinstrumental_vocal,gender_,gender_female,gender_male,gender_neutral,acousticelectric_,acousticelectric_acoustic,acousticelectric_electric,speed_,speed_high,speed_low,speed_medium,speed_veryhigh,speed_verylow
0,-0.938840,0.956250,0.369607,1.381203,0.595957,0.678478,0.157961,0.356487,3,2,3,1,1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False,False
1,-0.384126,0.650429,0.221210,1.155924,0.595957,-0.568269,-0.555240,0.552530,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,True,False,False
2,-0.191984,0.881922,-0.027839,2.193450,0.595957,0.311448,0.055928,0.684460,3,2,3,1,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False,False
3,0.507128,-0.667097,-0.832697,0.295620,-0.597329,-0.704553,-0.680978,0.209480,1,2,4,0,0,0,1,1,0,0,0,1,0,0,0,1,1,1,1,1,0,1,0,0,0,0,0,1,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False
4,0.203634,1.227820,0.577989,2.142250,2.173396,-0.311565,-0.362511,0.380979,1,1,2,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,True,False,False

#### Явных зависимостей не обнаружено

# CHECKPOINT 2

In [171]:
features_df

,duration_log_scaled,rate_downloads_total_log_scaled,rate_listened_total_log_scaled,likes_log_scaled,dislikes_log_scaled,playlisted_scaled,favorited_scaled,avgnote_scaled,genres_count,instruments_count,vartags_count,has_genres_pop,has_genres_rock,has_genres_electronic,has_genres_jazz,has_genres_,has_genres_indie,has_genres_folk,has_genres_chillout,has_instruments_,has_instruments_strings,has_instruments_piano,has_instruments_synthesizer,has_instruments_guitar,has_instruments_drums,has_instruments_electricguitar,has_vartags_voice,has_vartags_vocal,has_vartags_acoustic,has_vartags_,has_vartags_neutral,has_vartags_energetic,has_vartags_peaceful,has_vartags_happy,has_vartags_love,has_vartags_upbeat,lang_,lang_de,lang_en,lang_es,lang_fr,lang_id,lang_it,lang_pt,lang_zh,vocalinstrumental_,vocalinstrumental_instrumental,vocalinstrumental_vocal,gender_,gender_female,gender_male,gender_neutral,acousticelectric_,acousticelectric_acoustic,acousticelectric_electric,speed_,speed_high,speed_low,speed_medium,speed_veryhigh,speed_verylow
0,-0.938840,0.956250,0.369607,1.381203,0.595957,0.678478,0.157961,0.356487,3,2,3,1,1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False,False
1,-0.384126,0.650429,0.221210,1.155924,0.595957,-0.568269,-0.555240,0.552530,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,True,False,False
2,-0.191984,0.881922,-0.027839,2.193450,0.595957,0.311448,0.055928,0.684460,3,2,3,1,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,False,False,False,True,False,False
3,0.507128,-0.667097,-0.832697,0.295620,-0.597329,-0.704553,-0.680978,0.209480,1,2,4,0,0,0,1,1,0,0,0,1,0,0,0,1,1,1,1,1,0,1,0,0,0,0,0,1,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False
4,0.203634,1.227820,0.577989,2.142250,2.173396,-0.311565,-0.362511,0.380979,1,1,2,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,-1.223241,0.808178,1.279150,-0.142606,-0.597329,-0.654078,-0.621201,0.209480,3,1,1,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,True,False,False,False,False
1997,-0.518671,1.121424,1.757638,1.227162,0.595957,-0.608650,-0.610895,0.209480,2,1,3,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,True,False,False
1998,-0.025094,0.025684,1.087240,0.174907,-0.597329,-0.716812,-0.687162,0.552530,1,1,3,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,1,1,1,0,0,0,0,0,0,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,True,False,False
1999,0.819877,-0.855564,-0.917524,-0.142606,-0.597329,-0.685805,-0.645936,0.852665,1,1,3,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,1,0,0,True,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,True,False,False
2000,0.091234,-1.363264,-1.046666,-0.367885,-0.597329,-0.708880,-0.663457,0.724028,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,True,False,False,False,False,False,True,False,False

In [187]:
import numpy as np
import pandas as pd

# Метрики растояний + knn

## Косинусное растояние (все фичи)

In [197]:
X = features_df.to_numpy().astype(float)

def cosine_distance_matrix(X):
    norms = np.linalg.norm(X, axis=1, keepdims=True)
    Xn = X / norms
    sim = Xn @ Xn.T
    return 1 - sim

cos_dist = cosine_distance_matrix(X)

k = 5
near = []
nearest_distances = []

for i in range(len(X)):
    row = cos_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    nearest_distances.append(dists)

df_cosine = pd.DataFrame({
    "track": np.arange(len(X)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in nearest_distances],
    "d2": [x[1] for x in nearest_distances],
    "d3": [x[2] for x in nearest_distances],
    "d4": [x[3] for x in nearest_distances],
    "d5": [x[4] for x in nearest_distances],
})

df_knn_cosine

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,1784,2,126,257,1788,0.061944,0.069032,0.088345,0.096356,0.110399
1,1,1802,1715,753,1800,1736,0.052841,0.061782,0.065846,0.068159,0.088998
2,2,1784,0,1762,126,1308,0.046420,0.069032,0.097245,0.114762,0.122016
3,3,7,172,294,169,170,0.081198,0.089164,0.099585,0.102261,0.103402
4,4,1466,1739,758,233,506,0.036350,0.041154,0.070544,0.076854,0.082144
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,1497,1782,1282,1022,474,0.156274,0.163294,0.167310,0.180316,0.182463
1997,1997,1995,20,335,1345,1874,0.045317,0.052851,0.070878,0.080698,0.085676
1998,1998,13,14,1694,1734,1653,0.030765,0.051586,0.055255,0.070888,0.075131
1999,1999,208,253,40,1892,294,0.026159,0.056218,0.087044,0.089170,0.119148
2000,2000,1702,1703,1826,1827,280,0.015464,0.016905,0.023500,0.026355,0.032535

## Евклидово растояние (все фичи)

In [195]:
X = features_df.to_numpy().astype(float)

def euclidean(X):
    diff = X[:, None, :] - X[None, :, :]
    dist = np.sqrt((diff ** 2).sum(axis=2))
    return dist

eu_dist = euclidean(X)

k = 5
near = []
near_dist = []

for i in range(len(X)):
    row = eu_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    near_dist.append(dists)

df_knn_euclidean = pd.DataFrame({
    "track": np.arange(len(X)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in near_dist],
    "d2": [x[1] for x in near_dist],
    "d3": [x[2] for x in near_dist],
    "d4": [x[3] for x in near_dist],
    "d5": [x[4] for x in near_dist],
})

df_knn_euclidean

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,2,1784,126,257,1788,2.373545,2.420550,2.595207,2.848623,3.152380
1,1,1802,1715,753,1800,1736,1.210985,1.336882,1.347100,1.371289,1.568241
2,2,1784,0,1762,126,1308,2.103768,2.373545,2.772761,3.002336,3.118871
3,3,294,1280,172,7,293,2.773579,2.871100,2.886956,2.919358,2.955194
4,4,1466,1739,758,1135,506,1.498503,1.526052,2.014252,2.154740,2.427130
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,1497,1782,474,1022,1282,2.810715,2.827200,2.985157,3.005240,3.015702
1997,1997,1995,20,217,1345,1654,1.815884,1.877900,2.398079,2.448191,2.516726
1998,1998,13,14,1716,1694,1653,1.312146,1.662024,1.987674,2.033829,2.035269
1999,1999,208,253,1892,294,42,1.166938,1.720896,2.193633,2.479032,2.484932
2000,2000,1702,1703,1826,1827,280,0.720289,0.731029,0.861422,0.912572,1.027828

## MANHATTAN distance (все фичи)

In [193]:
X = features_df.to_numpy().astype(float)

def manhattan(X):
    diff = np.abs(X[:, None, :] - X[None, :, :])
    dist = diff.sum(axis=2)
    return dist

man_dist = manhattan(X)

k = 5
near = []
near_dist = []

for i in range(len(X)):
    row = man_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    near_dist.append(dists)

df_knn_manhattan = pd.DataFrame({
    "track": np.arange(len(X)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in near_dist],
    "d2": [x[1] for x in near_dist],
    "d3": [x[2] for x in near_dist],
    "d4": [x[3] for x in near_dist],
    "d5": [x[4] for x in near_dist],
})

df_knn_manhattan

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,1784,2,126,257,38,6.365679,6.827912,7.417289,7.435056,8.515589
1,1,1800,1802,1715,753,1646,2.246982,2.259621,2.282441,2.481609,2.785810
2,2,1784,0,257,1762,126,5.417226,6.827912,8.180352,8.785509,9.494235
3,3,88,7,294,293,172,7.849852,8.132163,8.307369,8.466082,8.993277
4,4,1739,1466,758,1639,1467,3.326904,3.408521,4.246985,4.987637,5.153253
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,1782,1497,1022,474,1282,8.253959,8.752338,9.261495,9.292826,9.727119
1997,1997,1995,20,1874,1654,217,4.017713,4.119882,6.037389,6.280120,6.863511
1998,1998,13,14,1841,1878,1694,2.572394,3.571960,4.068448,4.094683,4.635984
1999,1999,208,253,1892,1838,42,2.347750,4.161577,5.731089,5.895488,6.466365
2000,2000,1702,1703,280,1826,1827,1.336946,1.399126,1.764809,1.779054,1.802786

## Correlation distance (только для числовых фичей)

In [201]:
num_cols = [c for c in features_df.columns if c.endswith("_scaled") or c.endswith("_count")]
X_num = features_df[num_cols].to_numpy().astype(float)

def correlation(X):
    Xc = X - X.mean(axis=1, keepdims=True)
    Xn = Xc / Xc.std(axis=1, keepdims=True)
    sim = Xn @ Xn.T / X.shape[1]
    return 1 - sim

corr_dist = correlation(X_num)

k = 5
near = []
near_dist = []

for i in range(len(X_num)):
    row = corr_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    near_dist.append(dists)

df_knn_corr = pd.DataFrame({
    "track": np.arange(len(X_num)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in near_dist],
    "d2": [x[1] for x in near_dist],
    "d3": [x[2] for x in near_dist],
    "d4": [x[3] for x in near_dist],
    "d5": [x[4] for x in near_dist],
})

df_knn_corr

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,1344,1788,1488,1346,1108,0.028686,0.029307,0.031174,0.038056,0.050039
1,1,1736,49,1528,1768,25,0.040215,0.072299,0.085031,0.105504,0.105956
2,2,1784,367,319,177,0,0.036953,0.050363,0.052487,0.052506,0.053461
3,3,194,172,346,1280,1750,0.014815,0.022146,0.023613,0.025499,0.025678
4,4,1739,82,233,249,124,0.017803,0.031234,0.058604,0.065614,0.070455
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,1497,1282,207,1782,500,0.059109,0.066035,0.084496,0.088869,0.093613
1997,1997,1995,335,436,22,20,0.039346,0.044690,0.047796,0.049849,0.051044
1998,1998,1320,14,48,454,1899,0.030914,0.032650,0.036321,0.038559,0.039622
1999,1999,1892,1948,1297,346,1429,0.028247,0.029204,0.033141,0.042924,0.043133
2000,2000,1492,1703,1702,885,1809,0.025609,0.027627,0.028696,0.033821,0.036372

## Mahalanobis distance (только для числовых фичей)

In [203]:
S = np.cov(X_num, rowvar=False)
S_inv = np.linalg.pinv(S)

def mahalanobis(X, S_inv):
    n = X.shape[0]
    dist = np.zeros((n, n))

    for i in range(n):
        diff = X - X[i]
        dist[i] = np.sqrt(np.sum(diff @ S_inv * diff, axis=1))
    return dist

maha_dist = mahalanobis(X_num, S_inv)

k = 5
near = []
near_dist = []

for i in range(len(X_num)):
    row = maha_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    near_dist.append(dists)

df_knn_mahalanobis = pd.DataFrame({
    "track": np.arange(len(X_num)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in near_dist],
    "d2": [x[1] for x in near_dist],
    "d3": [x[2] for x in near_dist],
    "d4": [x[3] for x in near_dist],
    "d5": [x[4] for x in near_dist],
})

df_knn_mahalanobis

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,527,1784,353,1762,1199,1.960557,2.033510,2.344176,2.453904,2.500704
1,1,1736,1528,1768,1478,1738,0.857667,1.409549,1.414810,1.445381,1.456390
2,2,1784,227,251,220,164,1.694195,2.177613,2.229262,2.285188,2.356940
3,3,1280,194,1523,1845,287,1.226311,1.281217,1.356093,1.379056,1.455917
4,4,1739,124,1768,506,120,0.804846,1.222864,1.424813,1.540190,1.615524
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,1282,500,1782,207,1497,1.410390,1.643354,1.645285,1.652300,1.871835
1997,1997,1995,20,15,438,324,1.421133,1.463822,1.641795,1.665599,1.776476
1998,1998,282,1320,14,157,1734,1.146368,1.224622,1.367992,1.447821,1.481736
1999,1999,294,1948,1824,208,1892,1.276675,1.351894,1.373373,1.444773,1.487229
2000,2000,1702,1703,885,1875,1826,0.804997,0.891780,0.917424,1.024772,1.043881

## Jaccard distance (тольео для бинарных фичей)

In [205]:
bin_cols = [c for c in features_df.columns if c.startswith("has_") or c.startswith("lang_") or c.startswith("vocalinstrumental_") or c.startswith("gender_") or c.startswith("acousticelectric_") or c.startswith("speed") ]
X_bin = features_df[bin_cols].to_numpy().astype(int)

def jaccard(B):
    inter = B @ B.T
    row_sum = B.sum(axis=1, keepdims=True)
    union = row_sum + row_sum.T - inter

    sim = np.zeros_like(inter, dtype=float)
    np.divide(inter, union, out=sim, where=union != 0)

    return 1 - sim

jac_dist = jaccard(X_bin)

k = 5
near = []
near_dist = []

for i in range(len(X_bin)):
    row = jac_dist[i]
    row1 = np.argsort(row)[1:k+1]
    dists = row[row1]

    near.append(row1)
    near_dist.append(dists)

df_knn_jaccard = pd.DataFrame({
    "track": np.arange(len(X_bin)),
    "n1": [x[0] for x in near],
    "n2": [x[1] for x in near],
    "n3": [x[2] for x in near],
    "n4": [x[3] for x in near],
    "n5": [x[4] for x in near],
    "d1": [x[0] for x in near_dist],
    "d2": [x[1] for x in near_dist],
    "d3": [x[2] for x in near_dist],
    "d4": [x[3] for x in near_dist],
    "d5": [x[4] for x in near_dist],
})

df_knn_jaccard

,track,n1,n2,n3,n4,n5,d1,d2,d3,d4,d5
0,0,1788,257,38,1784,1022,0.142857,0.153846,0.153846,0.200000,0.230769
1,1,1136,1569,1646,1568,1258,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,1788,257,1784,1359,1477,0.142857,0.153846,0.200000,0.230769,0.230769
3,3,88,7,204,293,294,0.187500,0.235294,0.235294,0.266667,0.266667
4,4,428,1662,1263,1255,1252,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
1996,1996,74,1484,474,1971,1981,0.200000,0.333333,0.333333,0.333333,0.333333
1997,1997,1874,1430,19,550,596,0.071429,0.076923,0.142857,0.142857,0.142857
1998,1998,93,96,1216,1878,1998,0.000000,0.000000,0.000000,0.000000,0.000000
1999,1999,1999,253,525,1369,1838,0.000000,0.083333,0.083333,0.166667,0.166667
2000,2000,1136,1569,1646,1568,1258,0.000000,0.000000,0.000000,0.000000,0.000000

# Метрики качества

## Критерий релевантности: Трек считается релевантным, если совпадает хотя бы один жанр, хотя бы один инструмент, хотя бы один язык и хотя бы один вартег.

In [234]:
genre_cols = [c for c in features_df.columns if c.startswith("has_genres_")]
instr_cols = [c for c in features_df.columns if c.startswith("has_instruments_")]
lang_cols  = [c for c in features_df.columns if c.startswith("lang_")]
vartag_cols = [c for c in features_df.columns if c.startswith("has_vartags_")]

genre_mat = features_df[genre_cols].astype(int).values
instr_mat = features_df[instr_cols].astype(int).values
lang_mat  = features_df[lang_cols].astype(int).values
vartag_mat = features_df[vartag_cols].astype(int).values

genre_match = (genre_mat @ genre_mat.T) > 0
instr_match = (instr_mat @ instr_mat.T) > 0
lang_match  = (lang_mat  @ lang_mat.T) > 0
vartag_match = (vartag_mat @ vartag_mat.T) > 0

# критерий
rel_strict = (
    genre_match.astype(int)
    * instr_match.astype(int)
    * lang_match.astype(int)
    * vartag_match.astype(int)
)

np.fill_diagonal(rel_strict, 0)

def precision_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values
        rels = rel_mat[i, neigh]
        scores.append(np.mean(rels))
    return np.mean(scores)

def recall_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values   
        rels = rel_mat[i, neigh]
        total_rels = rel_mat[i].sum()
        if total_rels == 0:
            continue
        scores.append(rels.sum() / total_rels)
    return np.mean(scores)

def ndcg_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values
        rels = rel_mat[i, neigh]
        dcg = np.sum(rels / np.log2(np.arange(2, k+2)))
        ideal = np.sort(rel_mat[i])[::-1][:k]
        idcg = np.sum(ideal / np.log2(np.arange(2, k+2)))
        if idcg == 0:
            continue
        scores.append(dcg / idcg)
    return np.mean(scores)

knn_tables = {
    "cosine": df_knn_cosine,
    "euclidean": df_knn_euclidean,
    "manhattan": df_knn_manhattan,
    "mahalanobis": df_knn_mahalanobis,
    "correlation": df_knn_corr,
    "jaccard": df_knn_jaccard
}

results = []
for name, knn_df in knn_tables.items():
    p5 = precision_at_k(knn_df, rel_strict, k=5)
    r5 = recall_at_k(knn_df, rel_strict, k=5)
    n5 = ndcg_at_k(knn_df, rel_strict, k=5)
    results.append([name, p5, r5, n5])

df_fnl = pd.DataFrame(results, columns=["metric", "precision@5", "recall@5", "ndcg@5"])
df_fnl

        metric  precision@5  recall@5    ndcg@5
0       cosine     0.904648  0.006788  0.911121
1    euclidean     0.901149  0.006615  0.908368
2    manhattan     0.919740  0.006930  0.925815
3  mahalanobis     0.679860  0.004049  0.687980
4  correlation     0.670365  0.004139  0.676504
5      jaccard     0.918841  0.007881  0.909491

## Критерий релевантности: Трек считается релевантным, если совпадает не меньше 60% жанров, 60% инструментов и 60% вартегов, которые есть у исходного трека, плюс совпадает язык.

In [235]:
genre_cols  = [c for c in features_df.columns if c.startswith("has_genres_")]
instr_cols  = [c for c in features_df.columns if c.startswith("has_instruments_")]
vartag_cols = [c for c in features_df.columns if c.startswith("has_vartags_")]
lang_cols   = [c for c in features_df.columns if c.startswith("lang_")]

genre_mat  = features_df[genre_cols].astype(int).values
instr_mat  = features_df[instr_cols].astype(int).values
vartag_mat = features_df[vartag_cols].astype(int).values
lang_mat   = features_df[lang_cols].astype(int).values

genre_overlap  = genre_mat @ genre_mat.T
instr_overlap  = instr_mat @ instr_mat.T
vartag_overlap = vartag_mat @ vartag_mat.T
lang_overlap   = lang_mat @ lang_mat.T

genre_req  = np.ceil(genre_mat.sum(axis=1)  * 0.6)[:, None]
instr_req  = np.ceil(instr_mat.sum(axis=1)  * 0.6)[:, None]
vartag_req = np.ceil(vartag_mat.sum(axis=1) * 0.6)[:, None]
lang_req   = np.ceil(lang_mat.sum(axis=1)   * 0.6)[:, None]

rel_strict = (
    (genre_overlap  >= genre_req).astype(int) &
    (instr_overlap  >= instr_req).astype(int) &
    (vartag_overlap >= vartag_req).astype(int) &
    (lang_overlap   >= lang_req).astype(int)
).astype(int)

np.fill_diagonal(rel_strict, 0)

def precision_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values
        rels = rel_mat[i, neigh]
        scores.append(np.mean(rels))
    return np.mean(scores)

def recall_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values   
        rels = rel_mat[i, neigh]
        total_rels = rel_mat[i].sum()
        if total_rels == 0:
            continue
        scores.append(rels.sum() / total_rels)
    return np.mean(scores)

def ndcg_at_k(knn_df, rel_mat, k):
    scores = []
    for i in range(len(knn_df)):
        neigh = knn_df.iloc[i][["n"+str(j) for j in range(1,k+1)]].astype(int).values
        rels = rel_mat[i, neigh]
        dcg = np.sum(rels / np.log2(np.arange(2, k+2)))
        ideal = np.sort(rel_mat[i])[::-1][:k]
        idcg = np.sum(ideal / np.log2(np.arange(2, k+2)))
        if idcg == 0:
            continue
        scores.append(dcg / idcg)
    return np.mean(scores)

knn_tables = {
    "cosine":      df_knn_cosine,
    "euclidean":   df_knn_euclidean,
    "manhattan":   df_knn_manhattan,
    "mahalanobis": df_knn_mahalanobis,
    "correlation": df_knn_corr,
    "jaccard":     df_knn_jaccard
}

results = []
for name, knn_df in knn_tables.items():
    p5 = precision_at_k(knn_df, rel_strict, k=5)
    r5 = recall_at_k(knn_df, rel_strict, k=5)
    n5 = ndcg_at_k(knn_df, rel_strict, k=5)
    results.append([name, p5, r5, n5])

df_fnl = pd.DataFrame(results, columns=["metric", "precision@5", "recall@5", "ndcg@5"])
df_fnl

        metric  precision@5  recall@5    ndcg@5
0       cosine     0.568816  0.042488  0.599684
1    euclidean     0.541129  0.038748  0.572170
2    manhattan     0.594903  0.046328  0.624764
3  mahalanobis     0.289255  0.013669  0.301972
4  correlation     0.275962  0.012508  0.286798
5      jaccard     0.749125  0.071059  0.763638

# Наиболее эффективна метрика расстояния - это jaccard. 
# Также можно использовать cosine, euclidean и manhattan метрики. 
# correlation и mahalanobis дают результат значительно хуже.